In [1]:
import pandas as pd

df = pd.read_csv("Inference_Aleatoric_Test\Inference.csv",sep=',',index_col=None)

In [2]:
df

          y_hat  y_hat_sigma  y_true  aleatoric
0      0.972864     0.014058     1.0  -0.000076
1      0.003824     0.001969     0.0   0.000015
2      0.118586     0.023188     0.0   0.000301
3      0.817712     0.045367     0.0  -0.000107
4      0.965514     0.014609     1.0   0.000171
...         ...          ...     ...        ...
13438  0.000300     0.000257     0.0   0.000005
13439  0.951464     0.019249     1.0  -0.000141
13440  0.858233     0.057668     1.0  -0.000124
13441  0.118214     0.023182     0.0   0.000431
13442  0.016662     0.008517     0.0   0.000157

[13443 rows x 4 columns]